# Dependencies
markdown:         kramdown
highlighter:      rouge

# Gems
gems: [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Hyde-fi
tagline:          'Suomenkielinen käännös Jekyll-teemasta'
description:      'Suomenkielinen käännös <a href="http://jekyllrb.com" target="_blank">Jekyll</a>-teemasta.'
url:              http://hyde.getpoole.com
baseurl:          ''

author:
  name:           'Jonne Arjoranta'
  url:            https://twitter.com/jaranta

paginate:         5
paginate_path:    "/sivu:num/"

# Custom vars
sidebar_image:
version:          1.0.0

github:
  repo:           https://github.com/gitkrax/hyde-fi
